- integration/woocommerce.php
Fixing a JS bug within the product click trigger within the
gtm4wp_woocommerce_enhanced_ecom_product_click script output in
wp_footer
The script passed in a .length value instead of an object to the .find() function on line 564
> Fix to enable gtm4wp.productClickEEC

- .gitignore
- .scrutinizer.yml
- .travis.yml
- phpunit.xml
- tests/bootstrap.php
- tests/test-plugin.php
Took a little while longer than expected, had to rebuild and fork the php testing suite for CI tools to https://github.com/koconder/wordpress-test-template - Rebuilt the entire setup to support testing of Wordpress, along with multi-plugin co-dependency and other CI tools support.
Should enable us to get build errors and PHP code coverage and issues via Scrutinizer. #64 will be resolve through this PR
> Travis CI Support

- public/frontend.php
I'm using your (most excellent) GTM4WP inside of the Automattic Facebook Instant Articles plugin. Right now, to capture the output of `gtm4wp_wp_header_begin` i'm having to use `ob_start` and friends. Adding this `$echo` variable to control echo while always returning the results of the function means I can kick `ob_start` to the curb.
> Allow for optional echo of gtm4wp_wp_header_begin output

- public/frontend.php
PHP DOM doesn't accept the script tags as valid XML by default (really just the actual inlined JavaScript, it doesn't like the `&l=` for whatever reason). This PR wraps the JS in non-breaking `CDATA` tags which will then allow the script to be properly parsed via PHP DOM.
[More info](https://stackoverflow.com/a/66865/486182)
> Add CDATA tags to scripts

- public/frontend.php
- Added the same echo option as `gtm4wp_wp_header_begin` to `gtm4wp_wp_header_top`. 
- Fixed a bug introduced [here](https://github.com/duracelltomi/gtm4wp/commit/f5d922d5df1d6e81b7510c3508040ff30a0448ac#diff-3431ead545d30c94c19367781b8120e3L665) which used the incorrect variable name to add JS variables.
See also #80
> Support echo and return on gtm4wp_wp_header_top

- .travis.yml
Removing HHVM as Travis CI no longer supporting and builds will keep failing
> Patching Travis CI

- js/gtm4wp-woocommerce-enhanced.js
With some other plugins, that interfere with event processing, I get this error:
```
gtm4wp-woocommerce-enhanced.js:391 Uncaught TypeError: Cannot read property 'url' of undefined
at HTMLDocument.<anonymous> (gtm4wp-woocommerce-enhanced.js:391)
at HTMLDocument.dispatch (jquery.js:3)
at HTMLDocument.r.handle (jquery.js:3)
at HTMLDocument.<anonymous> (mango.js:formatted:5854)
at mango.js:formatted:5205
at m.every (<anonymous>)
at m.each (mango.js:formatted:5204)
at m.n.fn.trigger (mango.js:formatted:5853)
at n (mango.js:formatted:5899)
at r (mango.js:formatted:5904)
at s (mango.js:formatted:5921)
at HTMLScriptElement.<anonymous> (mango.js:formatted:5992)
at HTMLScriptElement.i.proxy (mango.js:formatted:5692)
```
> Check settings for undefined

- public/frontend.php
$min and $max were not defined, which should be fixed now. Double checked against http://www.grantburton.com/2008/11/30/fix-for-incorrect-ip-addresses-in-wordpress-comments/ from which it appears to be adapted.
> Fixed issue with IP-Proxy-Cluster Fix

- admin/admin.php
I have a site that's in development to add a Woocommerce component. The production site won't have Woocommerce installed for some time yet, my development server does. When switching between git branches for the production version of the site and the development version, gtm4wp gives a fatal error when the database thinks the plugin is active, but the plugin files aren't present. 
This simple fix just adds a `function_exists` call to the existing conditional checking if Woocommerce is active. This prevents a fatal error in this circumstance, and should not have any other impact on the plugin.
Thanks!
> Fix for fatal error if Woocommerce isn't installed

- common/readoptions.php
This fixes a bunch of notices I've been getting while setting up the plugin on a WP VIP environment.
> Ensure that variables are globals to be used everywhere.

- admin/admin.php
In 9d9e116bf692dd183fc90a8b2b03a6b205564f42 (#133), constants were added to allow for the hard-coding of container and environment IDs 🎉 . This included a warning message directly beneath the input fields in the plugin's settings, to alert the user as to the proper place to make the change.
However, the warning message assumes that the constant is defined in `wp-config.php`, which may not be the case: it is possible for the constant to be defined in various places:
- `wp-config.php`
- an mu-plugin
- theme file
In my use-case, I define the constants in the theme (will probably move to an mu-plugin soon) that use the development environment, and define the production variables in production's `wp-config.php`. While this likely won't be a problem in my case (because the constants ARE defined …
> Correct assumption made in constant warning messages

- integration/woocommerce.php
Shop Isle relies on nth-child(2) to hide a variant of the image set. However, by adding the product data related span before the product image via `before_shop_loop_item`, this causes the product image to become hidden. If we render the span with the `woocommerce_after_shop_loop_item` hook instead, we can preserve the span while avoiding this problem.
How it looks:
```
<li class="product type-product post-13462 status-publish first instock product_cat-foxyjoel product_cat-may-new-items product_cat-posters product_tag-damiya-foxyjoel product_tag-tokyomenace has-post-thumbnail shipping-taxable purchasable product-type-simple">
<a href="https://shop.moso.moe/product/damiya-foxyjoel-tokyomenace/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
<div class="prod-img-wrap"> …
```
> Render the data span after the image wrapper

- public/frontend.php
I fixed the order of the if/else statement to include the type="text/javascript" when html5 is NOT supported. In the existing version the type="text/javascript" was added for websites that support HTML5 and removed for websites that do not.
> Fixed html5 support detection

- public/frontend.php
I added these fields so that they could possibly be used as custom dimensions, metrics, events, etc in Google Analytics, BigQuery, etc, so that site owners could potentially use this data to determine the best day and time to post new posts, etc.
The following are new fields:
- pagePostDateDayName
- pagePostDateHour
- pagePostDateMinute
- pagePostDateIso
- pagePostDateUnix
> Added additional post day name & post date time fields in ISO8601 and Unix format

- integration/woocommerce.php
`new DateTime()` uses the default PHP timezone, while WP and WC might be using different. As a result, `$minutes` calculation might be incorrect if those timezones have different UTC offsets.
> WC max order age fix - use correct timezone to calculate time diff

- js/gtm4wp-form-move-tracker.js
I have gtm4wp installed on my site, and I get a lot of `event.target.closest is not a function` errors.
in "Additional Data" it says:
```javascript
[
{
currentTarget: [object HTMLDocument], 
isTrusted: False, 
target: [object HTMLDocument], 
type: focusin
}
]
```
and indeed - `HTMLDocument` doesn't have a `closest` function.
(try opening devtools and type `document.closest`).
Surprisingly this happens in Chrome.
I don't know when and why this happens, but when it does - the function fails and throws an error,
so I'd rather it failing silently.
Screenshots from my Sentry issue:
> fix "event.target.closest is not a function"

- integration/woocommerce.php
Fixes #282 $order->is_returning_customer() being undefined function.
In this context, $order is instance of WC_Order, while the method is_returning_customer() is only available in Order class which extends WC_Order.
WC_Order is available in both frontend and backend, but Order is used in Admin only - analytics. This PR reuses the return value of is_returning_customer in Order, which is basically directly calling DataStore with static method.
> Fix undefined is_returning_customer

- admin/admin.php
As a workaround or a temporary solution for #143. Instead of waiting for someone to develop this functionality, this way at least it can be overwritten with a simple hook;
```
add_filter( 'gtm4wp_admin_page_capability', 'hhf73_gtm4wp_capability' );
function hhf73_gtm4wp_capability( $capability ) {
$capability = 'moderate_comments';
return $capability;
}
```
> feat: new filter for capability override

- js/gtm4wp-woocommerce.js
When attempting to update the cart count, a `Uncaught ReferenceError: product_data is not defined` error occurred.
The error stemmed from a typo in the variable name being used.
This pull request resolves the issue by correcting the variable name to match its intended reference.
- Corrected the typo in the variable name from `product_data` to  `productData`.
> Fix: Reference Error due to Typo in Variable Name

- integration/woocommerce.php
The proposed modification aims to enhance the `GTM4WP_WPFILTER_ECC_PURCHASE_DATALAYER` and `GTM4WP_WPFILTER_EEC_ORDER_DATA` filters by including the WooCommerce order data.
Currently, while utilizing the `GTM4WP_WPFILTER_EEC_ORDER_DATA` filter, developers encounter limitations when attempting to enrich the data layer with additional information. Specifically, the absence of the order ID within this filter poses a challenge, requiring developers to resort to backtracking procedures to retrieve the order ID using order numbers.
This would be achieved by adding the `$order` argument to the filter, which would enable developers to access complete order data when modifying data layer values. The addition of the order object alongside the existing data layer would allow users to customize …
> Feature: Add order argument

- integration/woocommerce.php
Fixes #320 and probably #328.
The JS to push the purchase event to the dataLayer produces errors because the order id is not inserted as a string. See screenshot:
> Fix purchase event

- integration/woocommerce.php
1. **Set purchase-pushed flag on the canonical “order-received” path**
* In `gtm4wp_woocommerce_datalayer_filter_items()` inside the `is_order_received_page()` branch, we now set:
```php
$gtm4wp_woocommerce_purchase_data_pushed = true;
```
as soon as we start handling the thank-you page.
2. **Skip the fallback when we are on the real thank-you page**
* At the top of `gtm4wp_woocommerce_thankyou()`:
```php
if ( function_exists('is_order_received_page') && is_order_received_page() ) {
return;
}
```
This prevents the fallback path from racing the primary path.
3. **Added targeted diagnostics (guarded)**
* Temporary `error_log()` statements around key decision points (order load, key mismatch, age filter, `_ga_tracked` meta, cookie duplicate, failed status, and before/after …
> Fix: Prevent duplicate/blocked WooCommerce purchase pushes & add safer fallback
