duracelltomi/gtm4wp

- public/frontend.php
Hi Thomas, this is a pull request to resolve issue #5.
> Add Post_IDs only on Post, Pages and Attachment sites

- public/frontend.php
$headers type is array, not string
> $headers type is array, not string

- readme.txt
Mostly minor corrections, but some additional clarity added to some sections. This time, I hope the diffs are maintained.
> Revised readme further

- integration/woocommerce.php
Added two new filters that enable some products not to be sent to Google.
In our site, we are using this to not send bundled products, and only send the master bundle product.
> Enable filtering products from cart/order

- README.md
> Updated Readme.md for Travis CI build status

- public/frontend.php
> Fix wp_head/gtm4wp_wp_header_begin call

- admin/admin.php
- common/readoptions.php
- js/admin-subtabs.js
- public/frontend.php
Hi Thomas,
I took the liberty to propose a new branch including the remote ip option in the backend and pushing into the frontend. I do not have complete insights in your codebase, so please do check carefully.
> Visitor IP

- js/gtm4wp-woocommerce-enhanced.js
Google Analytics has an 8kb request size limit on tracking data requests, and if a page has too many WooCommerce products displayed on it, it will exceed the packet size limit due to all the product impression data that is added to the singe dataLayer event. Apparently when this happens there is no warnings from GA of any kind, the packet is simply not sent. We only noticed this because we had a sudden sharp loss in page views when we added some extra products to our shop page.
This can be addressed by splitting the product impression data into multiple events, such that each one is below the limit. I've been forced to patch the plugin manually on our site with the change contained in this pull request but it would be great if we could have a fix for this added to the next update to the …
> Fix GA data being dropped due to 8kb limit for product impression data

- js/gtm4wp-users.js
> Updating JavaScript for Compabilitiy

- admin/admin.php
No need for additional parameters.
Discovered by @phpstan
> admin-subtabs script is already registered

- public/frontend.php
@duracelltomi Powered by @phpstan
> Fix var_export calls

- admin/admin.php
- common/readoptions.php
- integration/woocommerce.php
- js/admin-subtabs.js
Submitting this request on behalf of @erikmolenaarnl  to resolve the issue #118
> prevent duplicate transaction tracking on woocommerce order received page 

- js/gtm4wp-contact-form-7-tracker.js
I reduced the repetition because of the DRY principle.
> refactor: Removed individual ctf7 event listeners

- js/gtm4wp-woocommerce-enhanced.js
Read link's target attribute and open product from product's list in a new tab if `target="_blank"` is added.
Resolves #259
> Read link's target attribute

- integration/woocommerce.php
Fixes CRITICAL Uncaught Error: Call to a member function get_meta() on null in /duracelltomi-google-tag-manager/integration/woocommerce.php:842
> Fixes CRITICAL Uncaught Error: Call to a member function get_meta() on null

- js/analytics-talk-content-tracking.js
- public/frontend.php
The goal is to removing jquery when is not necessary. For performence.
> removing jquery dependency for content tracking

- integration/woocommerce.php
add product stockstatus to integration woocommerce
> add product stockstatus

- admin/admin-tab-integrate.php
- admin/admin.php
There are some missing strings for localization and I added a quick fix in the code.
> fix the i18n missing strings

- public/frontend.php
Fixes https://github.com/duracelltomi/gtm4wp/issues/323
> FIX: do not load GTM container when OFF and console.log OFF

- js/gtm4wp-woocommerce.js
This PR solves the issue https://github.com/duracelltomi/gtm4wp/issues/391
> fix: product_qty defined in woocommerce script
